### ISSUE TITLE
Timeouts from the storage should be handled by the InMemoryMessageMatcher

### ISSUE THREAD

**Issue by alprema** [Abc-Arbitrage/Zebus.Persistence#3]
Since the `IStorage.Write()` method returns a Task, it should be waited by [InMemoryMessageMatcher](https://github.com/Abc-Arbitrage/Zebus.Persistence/blob/master/src/Abc.Zebus.Persistence/Matching/InMemoryMessageMatcher.cs#L164) in order to catch exceptions.

**Comment by ltrzesniewski** [comment]
This issue was moved to Abc-Arbitrage/Zebus#73
